### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by 158627746** [tarashakhurana/detecting-invisible-people#2]
I apologize for my previous rudeness, but I do have some issues that I would like to discuss rationally with you. as follows.
First, I think the code in the paper that is open sourced for others to study should at least be available or error-free, not just use github as our own code repository.

There are a lot of code writing errors in this project. 
1.Where is the definition or introduction of the _function get_mask_from_bbox()_ in line 83 of the _tracker.py_ file in the _deep_sort_ folder?
2.What’s the meaning of the parameter “tn=self.tn” of the function _update()_ in line 95?
3.Where is the definition or call of the function _compute_mean_depth_from_mask()_ in line 434?
4.Where is the definition of the variable _only_extrapolate_ in line 161 of the _tracker_mask.py_ file?
5.Does the function _project()_ require a parameter called _temporal_noise_ in line 301 of the _kalman_filter.py_ file?
6.and so on
Please double check and update the code carefully when you have time.
Also, I have a question, are the results stated in the paper based on this project??

Second, the project is not coding standard. 
1.There are a lot of unused imports in the project, such as “import ast” in detection.py, cv2 in _kalman_filter.py_, and so on.
2.In addition, in the _kalman_filter.py_ file, the type of _tn_ was originally int, later in the line 92 tn became a dict? Shouldn't the correct way to write line 80 be “if not tn”?

Finally,I previous said that the necessary comments are missing in the code, like 
1.what exactly is the meaning of _tn_ mentioned above? Whether it is a glyph or a dict with specific meaning is not given in the code. 
2.In line 132 of Kalman_filter.py, the function _project()_ requires 5 parameters. Why are there no corresponding annotations for the other 3 parameters except the _mean_ and _covariance_ parameters that were originally in the _deep_sort_ project? 
There are many such cases, please check carefully when you have time, and add this part of the note if you can.

Detecting Invisible People is a funny stuff, I wanted to peruse the code for this project, but it was kind of bad, and reading it made me so irritable, hence i raise yesterday's issue. I think not only we must learn to be a rational person, also we should be rational and rigorous with our own research and works. The above are some of the questions I have raised. I am looking forward to your reply.

**Comment by tarashakhurana** [comment]
Hey, thanks for your detailed questions! Note that this is a research codebase, and not intended for production. It includes code only for our final method, not any of the intermediate ablations in the main paper or the supplementary material. This code was proof-run to reproduce the final numbers in the paper. If you have errors specific to your environments and python versions, please feel free to open new issues for each and we can debug them together.

**Code writing errors:**
1, 2, 3, 4. These belong to the person-masks ablations in the supplementary for which support was not provided. These functions are never called and so please feel free to remove these from the code.
5. Thanks for pointing this out! Fixed it now.
6. Happy to accept pull requests for anything else you find.

**Coding standard:**
1, 2. Happy to accept pull requests that change these in the code. `tn` is set [here](https://github.com/tarashakhurana/detecting-invisible-people/blob/bf63fae4178a25fef58b7f1a41e9e587cd786702/deep_sort_app.py#L419) according to the experiment configuration.

**Comments**
1. `tn` is either -1 or a dict. You can also change it to `None` instead of -1 and submit a pull request!
2. The variables should match the terminology used in the paper. `tn` stands for temporal noise.

Thank you for taking the time!
